#!/usr/bin/expect

#Usage sshlogin <host> <ssh user> <ssh password> 

set timeout 60

spawn ssh [lindex $argv 1]@[lindex $argv 0] hostname

expect "yes/no" { 
	send "yes\r"
	expect "*?assword" { send "[lindex $argv 2]\r" }
	} "*?assword" { send "[lindex $argv 2]\r" }

interact
